Create PlayerBlips.json
altmp/altv-hub pull request #49
Opened 2020-10-15 12:51 UTC by VnX-SolidSnake

# Please double check your fork for the following:

- [X] Creating this pull request.
- [X] Cover image is uploaded on imgur.
- [X] Cover image ends in `.jpg, .png, or .jpeg`
- [X] Tags of resources only includes tags supplied on front-page

**Fill each step with 'X' if requirements are met.**

2020-10-17 19:55 UTC, Stuyk requested changes

2020-10-17 19:55 UTC, Stuyk commented on resources/Solid_Snake/PlayerBlips.json
> +  "cover": "https://imgur.com/0GCBzvD",
Fix image extension.

2020-10-17 19:55 UTC, Stuyk commented on resources/Solid_Snake/PlayerBlips.json
> +  "tags": ["c#", "javascript", "playerblips", "blips", "player", "venox", "solid_snake", "csharp"],
Use tags listed on README only.

2020-10-18 12:47 UTC, VnX-SolidSnake reviewed
Done

2020-10-18 13:58 UTC, merged